config/routes.rb
Rails.application.routes.draw do
  root to: 'todo_lists#index'

  resources :todo_lists do
    resources :todo_items
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :profiles
  resources :users
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  # Add default_scope to both TodoList and TodoItem models
  #to always return collectons from the database ordered by
  # due dates with earliest dates first.

  default_scope { order :due_date }
  scope :completed_todos, -> { where(completed: true) }
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_list_path(@todo_list), notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<div class="well col-md-8 col-md-offset-2">
<%= form_for([@todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field input-group mb-3">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field input-group mb-3">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field mb-3">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
 <% if !@todo_item.new_record? %>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit 'Save Todo Item', class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/todo_items/_todo_items.html.erb
<div class="todo_item">
  <div>
    <%= content_tag :span #{todo_item.title}, class: "todo-item-title" %>
    <%= link_to "Delete Todo Item", todo_list_todo_item_path(@todo_list, @todo_item) %>
  </div>
  <div><%= simple_format todo_item.title %></div>
</div>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<div class="row justify-content-md-center">
  <%= render 'form' %>
</div>

<%= link_to 'Show', [@todo_list, @todo_item] %> |
<%= link_to 'Back', @todo_list %>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @todo_list %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Due date</th>
    <th>Description</th>
    <th>Completed</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @todo_item.title %></td>
    <td><%= @todo_item.due_date %></td>
    <td><%= @todo_item.description %></td>
    <td><%= @todo_item.completed %></td>
  </tr>
  </tbody>
</table>


<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, @todo_item) %>
<%= link_to 'Back', todo_list_path(@todo_list) %>